server:
  servlet:
    context-path: /
  port: 8080
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  main:
    banner-mode: 'OFF'
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

backend:
  services:
    customerUrl: http://localhost:8081/
    productUrl: http://localhost:8082/
    orderUrl: http://localhost:8083/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
  instance:
    prefer-ip-address: 'true'