server:
  servlet:
    context-path: /
  port: 8085
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  main:
    banner-mode: 'OFF'
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: ${SPRING_JPA_TIMEZONE:America/Sao_Paulo}
    hibernate:
      ddl-auto: update
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
  datasource:
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:root}
    tomcat:
      max-active: ${SPRING_DATASOURCE_MAX_ACTIVE:10}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/dbpayment?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
  rabbitmq:
    username: "admin"
    password: "passw123"
    port: 5672
    host: localhost

rabbitmq:
  exchange: shoesclick_exchange
  notification:
    queue: mq_notification
    routingKey: notification_routingkey
  payment:
    queue: mq_payment
    routingKey: payment_routingkey

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

backend:
  services:
    customerUrl: http://localhost:8081/
    productUrl: http://localhost:8082/
    orderUrl: http://localhost:8083/
  gateway:
    bankSlipUrl: https://a0bb02cd-0bbc-46d6-915b-36835334ba89.mock.pstmn.io
    pixUrl: https://a0bb02cd-0bbc-46d6-915b-36835334ba89.mock.pstmn.io
    cardUrl: https://a0bb02cd-0bbc-46d6-915b-36835334ba89.mock.pstmn.io